security:
    encoders:
        App\Entity\User:
            algorithm: bcrypt
    providers:
        user_provider:
            entity:
                class: App\Entity\User
                property: username
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: ~
            http_basic: ~
            provider: user_provider
            form_login:
                csrf_token_generator: security.csrf.token_manager
                login_path: login
                check_path: login
                default_target_path: home
                always_use_default_target_path: true
            logout:
                path:   /logout
                target: /login
            switch_user: { role: ROLE_ADMIN }
    access_control:
        - { path: ^/login, roles: 'IS_AUTHENTICATED_ANONYMOUSLY' }
        - { path: ^/admin, roles: 'ROLE_ADMIN' }
        - { path: ^/, roles: ['ROLE_USER', 'ROLE_ADMIN'] }
