<?php

namespace App\Repository;

use Doctrine\ORM\EntityRepository;
/**
 * ChargeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ChargeRepository extends EntityRepository
{
    /**
     * all charge with expired date
     * @return array
     */
    public function findAllExpired() {
        return $this->createQueryBuilder('c')
            ->where('c.deadline < :today')
            ->setParameter('today', new \DateTime())
            ->getQuery()
            ->getResult();
    }
}
