<?php

namespace App\Repository;

use Doctrine\ORM\EntityRepository;
/**
 * CondominiumRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CondominiumRepository extends EntityRepository
{
}
