<?php

namespace App\Repository;

use App\Entity\User;
use Doctrine\ORM\EntityRepository;
/**
 * NotificationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NotificationRepository extends EntityRepository
{
    public function findNotifToday(User $user) {
        return $this->createQueryBuilder('c')
            ->where('c.createdAt <= :today AND c.user = :user')
            ->setParameter('today', new \DateTime())
            ->setParameter('user', $user)
            ->orderBy('c.createdAt', 'DESC')
            ->getQuery()
            ->getResult();
    }
}
